language: node_js
node_js:
  - "node"

cache: yarn

script: yarn run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GH_TOKEN
local_dir: dist
on:
  branch: main

after_success: 
- cd ./dist
- git init
- git add .
- git commit -m "Automatically update from travis-ci"
- git push --quiet --force  "https://$GH_TOKEN@$GH_REF" main:${P_BRANCH}